{
 "title": "Wallet service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"wallet-service\", status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"wallet-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"wallet-service\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"wallet-service\", area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"wallet-service\", area=\"heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"wallet-service\", area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"wallet-service\"}",
     "legendFormat": "hikaricp_connections"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"wallet-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}